### ISSUE TITLE
Does the LICENSE of the source code belong to the EULA?

### ISSUE THREAD

**Issue by linghengqian** [dyrnq/docker-doris#25]
- I noticed that Git currently doesn't have a specific LICENSE file, so can I understand that this is some kind of EULA?
- I don't care about the LICENSE of the various layers of the Docker Image, because most developers don't have the energy to try to distribute SBOM files.
- I'd be happy to see a solution beyond https://github.com/apache/doris/issues/9426 .

**Comment by dyrnq** [comment]
- LICENSE All are OK
- This repo created during my learning apache-doris.
